### ISSUE TITLE
Set status using checks

### ISSUE THREAD

**Issue by gr2m** [wip/app#102]
Instead of setting a status directly, the new version of WIP will use the new checks API with custom actions. Check runs have two benefits

1. **A custom UI:**  
  ![image](https://user-images.githubusercontent.com/39992/42129900-bf62699a-7c87-11e8-85da-605ba21be00b.png)
  The "details" link in the pull request checks list links to that UI. In there we can explain why the pull request was set to "pending". That will come in handy when introducing configuration (#96)
2. **Custom actions:**   
  We can use a custom action to manually override the "pending" status. That will become helpful when WIP is configured to look for terms in commit messages. Once the pull request is considered ready, the author does not need to clean up the commits, they can just override the status to "ready". That should help us address https://github.com/wip/app/issues/53

Unfortunately the custom actions are only visible to users with write access to the repository. In order to allow an author of a pull request without write access to the repository to override the status we’d need to manually explain that they need to add an HTML comment to the pull request body which looks something like this

```html
@wip ready for review
```

Checks will also require to add read/write permission to check runs

**Comment by tomkerkhove** [comment]
Love it - Certainly the capability that you can override it in case things are not correct but you need to move on.

Are there plans to provide a "reason" why it is being overriden?

**Comment by tomkerkhove** [comment]
Small word of feedback - Maybe make the used configuration collapsable similar to how Travis CI does this?

Example:
![image](https://user-images.githubusercontent.com/4345663/42134768-06ecdf2e-7d42-11e8-8dad-4ac85812caf2.png)

**Comment by gr2m** [comment]
> Maybe make the used configuration collapsable similar to how Travis CI does this?

Oh I didn't know I can do this! Yeah I might do this if it becomes too much, good to know it’s possible

**Comment by gr2m** [comment]
> Are there plans to provide a "reason" why it is being overriden?

No, I don’t see a need for it. What would be use cases for you?

Note that an important aspect of the WIP app is to be used as a reference implementation of a GitHub App, now including marketplace and configuration features. I try to strike a good balance between usefulness and code complexity

**Comment by tomkerkhove** [comment]
In that case it might be less interesting but given somebody is overriding the tool so he can merge in it might be interesting to know why he is doing that.

But given what you said I can see that it's not worth the effort.

**Comment by gr2m** [comment]
### Checks are here 🎉

I’ve pushed it to [the beta version of the WIP app](https://github.com/organizations/wip/settings/apps/wip-beta) and would love all your help testing it, please see my update in the [🤖📯 Updates](https://github.com/apps/wip-beta) issue.

Thank you all for your patience and help 🙏

**Comment by gr2m** [comment]
Here we go! Sign up for any plan to get the checks https://github.com/marketplace/wip
