### ISSUE TITLE
[Question][Off-Topic]: Where are the "Bookmark" and "Pre-release" tags coming from? (README.md gif)

### ISSUE THREAD

**Issue by micgro42** [wip/app#104]
In the gif included in your readme are two tags visible between the pull request status and the username. AFAICT these are not part of vanilla GitHub. Which GitHub app/browser extension/integration is providing these icons/tags?

**Comment by gr2m** [comment]
Oops. It's a pre-release feature that is not available to all GitHub users. It should have not been in the GIF. I’ll make a new one to remove it. I can’t say anything else about it I’m afraid, but thanks for opening the issue :)
