### ISSUE TITLE
PR is still pending even after removing "WIP" in title

### ISSUE THREAD

**Issue by EdmundMai** [wip/app#106]
My PR is blocked by WIP even after I remove "WIP" in the title.

https://github.com/oysterprotocol/webnode/pull/150

**Comment by gr2m** [comment]
the reasons is this commit message:

> add unhappy path for treasure claiming wip

I’ve a nearly ready pull request (#94) that will add an explanation where it found the "WIP". It will also introduce an "override" so that you won’t need to squash your commits to set the status to success
