### ISSUE TITLE
WIP Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by jchannon** [wip/app#109]
Hi

We think as of today all our PRs are set with the status as shown in the title.

Any ideas why it might be this?

Our organisation is called VQComms

Thanks

**Comment by gr2m** [comment]
Is it possible that you uninstalled the WIP app? I don’t see any requests for VQComms since July 20

**Comment by jchannon** [comment]
i removed it as a required check from one repo to get a pr in then put it
back again

**Comment by gr2m** [comment]
Can you check if you see WIP listed at `https://github.com/VQComms/<repo>/settings/installations`?

**Comment by jchannon** [comment]
I can see it at
https://github.com/organizations/VQComms/settings/installations

**Comment by jchannon** [comment]
And at https://github.com/VQComms/VQ/settings/installations

**Comment by gr2m** [comment]
could you update one of the PRs at https://github.com/VQComms/VQ/pulls? I just want to check if WIP receives the events

**Comment by jchannon** [comment]
https://github.com/VQComms/VQ/pull/2830 has just been updated for you.
thanks

**Comment by gr2m** [comment]
I redelivered the hook, it seemed to have worked now? Can you check if the status was updated on VQComms/VQ#2830?

**Comment by jchannon** [comment]
It was. All good now! Thanks. Is there anything we can do in case this
happens again to save you investigating

**Comment by gr2m** [comment]
Let me know if it happens again please. I fear there is a bug somewhere, I just didn’t catch it this time. Thanks again for your help!

**Comment by jchannon** [comment]
Thank you!
