### ISSUE TITLE
🐛 Closed PRs show the pending dot

### ISSUE THREAD

**Issue by gldraphael** [wip/app#117]
Firstly thanks for this app. I just installed it and it's great.

The closed PRs, however, now show the pending (yellow, brown?) dot instead of the green tick that was previously there. [Link](https://github.com/gldraphael/evlog/pulls?q=is%3Apr+is%3Aclosed).

Possibly related: #98

**Comment by gr2m** [comment]
Hey @gldraphael did you see it happen on new PRs? It might just have been a hiccup. I’ll close the issue because there is not much I can do about it, but please feel free to keep commenting

**Comment by gldraphael** [comment]
Okay so the PRs closed before the app was installed are the affected ones - the status changed from green to pending.
