### ISSUE TITLE
WIP app/bot keeps pending mark

### ISSUE THREAD

**Issue by rarkins** [wip/app#118]
I first noticed this yesterday, although it could have been going for longer. I renamed a long-existing PR to remove 'WIP' from its title and the WIP status check failed to turn green. I made more commits to the branch and noticed it did turn green later, but I since have had it turn back to pending after further commits - none of which are to do with the PR title. I have now merged the PR so cannot continue testing.

**Comment by tooomm** [comment]
Also realized some inconsistencies in https://github.com/badges/shields/pull/2010#issuecomment-416904721

**Comment by gr2m** [comment]
sorry for the trouble @rarkins @tooomm! I’ve been out for parental leave and catching up with things. I have error logs and error reporting, I will watch them now. Did it occur again for you? I think these were just hiccups. I’ll soon update to a new version to make WIP ready for the marketplace which I hope will also help with these hiccups

**Comment by rarkins** [comment]
@gr2m no problem at all, and congratulations to everyone in the family!

I haven’t noticed the problem again since. I noticed some undelivered/rejected webhooks to a zeit app of my own around the same time too. Pity though it wasn’t self-healing despite my attempts - doing so would be a good fallback.
