### ISSUE TITLE
Feature Request: Supporting customizable per-repo/per-branch required/banned labels on PRs in general

### ISSUE THREAD

**Issue by dpoeschl** [wip/app#121]
I've been thinking about writing my own GitHub app to require or ban certain labels on PRs, configurable per-branch. I know you're trying to keep this one simple based on the conversation in https://github.com/wip/app/issues/24, but that was a while ago and I figured I'd ask about it anyway. 😄 

As an example, for https://github.com/dotnet/roslyn, we have some labels that we'd want to **prevent** merging like "PR for personal review only" (and others). Or, on _some_ branches that require management approval, we'd **require** the "Approved to merge" label.

Is that something you'd be interested in supporting within WIP? Or using the same codebase with a different app name? I'd be happy to help with this effort if you think it'd be a good fit. If not, I can try to make my own app, but I'd rather integrate it here if possible.

Thanks for considering!

**Comment by gr2m** [comment]
Have you seen https://github.com/wip/app/pull/94? It will introduce configuration of the terms and locations to look at, so you could define terms that WIP will only look in the labels, but not in the title or commit messages. Will that be helpful?

**Comment by gr2m** [comment]
### [Configuration is here](https://github.com/wip/app#configuration) 🎉

I’ve pushed it to [the beta version of the WIP app](https://github.com/organizations/wip/settings/apps/wip-beta) and would love all your help testing it, please see my update in the [🤖📯 Updates](https://github.com/apps/wip-beta) issue.

There is no way to configure "required" labels at this point though, it can only check if configured terms can be found in labels

Thank you all for your patience and help 🙏

**Comment by gr2m** [comment]
Let me know if you are still interested in this
