### ISSUE TITLE
The new app from marketplace is unreliable 

### ISSUE THREAD

**Issue by mauroservienti** [wip/app#136]
I’m facing a lot of false positives and WIP checks failures since I installed the latest version.
Here is a PR blocked by WIP even if it’s not WIP 
https://github.com/mauroservienti/designing-a-ui-for-microservices-demos/pull/29

**Comment by janl** [comment]
we’re also seeing extended wait times for WIP to report. Often 10 or more minutes, sometimes the status never arrives.

**Comment by siavashs** [comment]
We're facing similar issues.

**Comment by gr2m** [comment]
There are a lot of DNS related issues on now, they are looking into it.

> we’re also seeing extended wait times for WIP to report. Often 10 or more minutes

I don’t keep a queue of events, that usually means that GitHub had sent the events with a delay as they did during and after their recent outage

**Comment by gr2m** [comment]
Can you please post the pull request URLs where you have seen the problems? If the repository is private and you are not comfortable posting the URLs here you can send me a twitter DM: https://twitter.com/gr2m

**Comment by gr2m** [comment]
Oh also let me know if you accepted the updated permissions or not

**Comment by mesaugat** [comment]
Hello @gr2m, has the free version stopped working with GitHub labels like `wip` and `do not merge`? It used to work previously. Do we need to upgrade to the PRO version?

**Comment by gr2m** [comment]
@mesaugat yes, see the update at https://github.com/wip/app/issues/89#issuecomment-432447327

**Comment by gr2m** [comment]
I’ve found one problem that caused problems for pull requests that still hat a status set from the old app, that was resolved via https://github.com/wip/app/pull/138.

I also see much fewer DNS errors, though I haven’t heard an update from Zeit. If you still see any problems please make new issues with explicit descriptions :) Cheers!
