### ISSUE TITLE
After uninstall, bot remains in open PRs?

### ISSUE THREAD

**Issue by Kebap** [wip/app#140]
Unfortunately, I had to uninstall WIP bot from one of my repositories here.

However WIP is still shown in a few open PRs and seems to block the merge.
Is this expected behavior? How to remedy the situation? Thanks in advance!

Example: https://github.com/Mudlet/Mudlet/pull/1797

**Comment by gr2m** [comment]
Unfortunately, this is a limitation of GitHub apps. The moment you uninstall an App from your repository, the app has no longer any permission to do anything in your repository. 

What you can do though is to remove the WIP status from being required before merging a pull request:

![image](https://user-images.githubusercontent.com/39992/47663508-6e5e1800-db5a-11e8-92b2-a3e9b20dac5c.png)

That setting is in Your repository -> Settings -> Branches -> Branch protection rules

**Comment by gr2m** [comment]
I wonder where I could put an FAQ for questions such as this 🤔

**Comment by gr2m** [comment]
Also if you push another commit the WIP status might disappear, I’m not 100% sure though, I’d love to know if you gave that a try :)

**Comment by Kebap** [comment]
Will do, then report back here.

FAQ, maybe in a github wiki?

**Comment by Kebap** [comment]
Pushing a commit does indeed fix the situation and make WIP disappear! :tada: 

Some screenshots for your comparison:

Before:
![image](https://user-images.githubusercontent.com/117238/47672513-882b4980-dbb2-11e8-9ee6-94fb3400df4d.png)

After:
![image](https://user-images.githubusercontent.com/117238/47672590-b4df6100-dbb2-11e8-817e-5bcf5efaf02a.png)

**Comment by gr2m** [comment]
Wonderful, thank you for sharing the screenshots!
