### ISSUE TITLE
Stuck "In progress"

### ISSUE THREAD

**Issue by NicolasBonduel** [wip/app#142]
Hello,

I tried to install this app on a couple of our repositories.
It seems however that it never finishes to complete its task.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/6507454/48416194-cd717e80-e74f-11e8-93d8-88de8c08db53.png">

Anything I could be doing wrong?

**Comment by gr2m** [comment]
Hey Nicolas, can you share URLs to the pull requests? Even if it’s private, knowing the repository owner / name / pull request number helps me find out in the logs what’s happening

**Comment by NicolasBonduel** [comment]
I sent you a private message (through Twitter.)
