### ISSUE TITLE
WIP not working?

### ISSUE THREAD

**Issue by rgomez90** [wip/app#144]
I use this WIP app since a few months. Always worked as expected.

Today I create a new **private** repo and found WIP does not work in the repo. I already used WIP with private repos before without any issues.
I've tried to:
* "reinstall" the app
* tried to grant "sprecific" project access
* changed again to grant access to all project
* create a new PR

but nothing triggers the check... 😭 

-----------------------------------

Some screenshots
### **PR page**
![image](https://user-images.githubusercontent.com/12009909/48687061-9f60c400-ebbf-11e8-898f-00b0a16fdbe7.png)

### **Repo's branch protection configuration**

![image](https://user-images.githubusercontent.com/12009909/48687144-08e0d280-ebc0-11e8-8c92-6da5e542f352.png)

---------

**I also noticed in the same repo, the first PR made (also used WIP) not all commits made were "checked".**

![image](https://user-images.githubusercontent.com/12009909/48687179-36c61700-ebc0-11e8-85fc-f6e2ca569223.png)

Just for info, the repo does NOT have any checks more, the only check for now is the WIP check.
I suppose I am missing sth or doing sth wrong that triggers this behaviour?

Hope you can give me some advice 😄

**Comment by gr2m** [comment]
I see a spike of request errors in the WIP logs between 7pm & 9pm pacific time, seems to be okay again. Could you please try to just edit your pull request title? That will trigger the WIP check again

**Comment by rgomez90** [comment]
Working again like a charm 😄 😄 Thank you @gr2m !

**Comment by gr2m** [comment]
Thanks for your patiences :)
