### ISSUE TITLE
Document how to configure WIP installation using a single .github repository

### ISSUE THREAD

**Issue by gr2m** [wip/app#150]
You can do that by creating a `.github` repository and put a `.github/wip.yml` file in there. This became possible via https://github.com/probot/probot-config/pull/16

**Comment by mwarkentin** [comment]
@gr2m this sounds awesome. I've tried to configure it globally for our organization but it doesn't seem to be picking it up - any pointers?

Here's our `.github` repo:
![](https://s3.amazonaws.com/mwarkentin-snaps/.githubwip.yml_at_master__waveaccounting.github_2018-11-30_16-17-56.png)

Here's a recent wip check showing that it's using the default config:

![](https://s3.amazonaws.com/mwarkentin-snaps/DO_NOT_MERGE_Run_watchman_before_deploying_by_mwarkentin__Pull_Request_2774__waveaccountingidentity_2018-11-30_16-18-13.png)

**Comment by gr2m** [comment]
I might need to update the Probot version and redeploy. I’ll look into it tomorrow

**Comment by gr2m** [comment]
I’m sorry Micheal, WIP is not using `probot-config` yet, I’ll fix that tomorrow and make sure it works as described :)

**Comment by gr2m** [comment]
hmmm worked when I tested locally but not in production: https://github.com/gr2m/sandbox/pull/66

Must be Friday night :D I’ll have another look tomorrow

**Comment by gr2m** [comment]
I guess sometimes it’s just good to sleep over it, and then it magically works ✨ 
https://github.com/gr2m/sandbox/pull/67/checks?check_run_id=36767910

Can you please give it a try?

**Comment by mwarkentin** [comment]
I can check on this Monday, thanks!
