### ISSUE TITLE
🚧 attached to word isn't recognized

### ISSUE THREAD

**Issue by HaydenMeloche** [wip/app#160]
Found this (bug?) when I was playing around.
![image](https://user-images.githubusercontent.com/15106748/49357785-6126d280-f69e-11e8-836f-af162611c112.png)

If 🚧 is attached to another word like `🚧hi`, the WIP bot won't recognize that it's their.

I can look into this if you'd like @gr2m 😄

**Comment by gr2m** [comment]
Oh that would be great, thanks! Using regular expression with emoji is tricky so I had work around it a bit: https://github.com/wip/app/blob/d91e3104f03d706d567d3f787dd97095066dc8e3/lib/common/match-terms.js#L3-L16

You can add a unit test for the `match-terms.js` function only for that edge case

**Comment by HaydenMeloche** [comment]
I've been thinking about this issue @gr2m, do you have any ideas on how to tackle this? I was thinking of extending it so if no match is found. It will then do an emoji regex lookup and if one is returned then look to see if that emoji is in the list.
Not sure if this is the best way of approaching this though.

Any suggestions?

**Comment by gr2m** [comment]
Hmm maybe we could replace all emoji using the "gemoji" package and then use a simple regex instead of the current workaround?

Or we check if the term is an emoji. If it is, we check if it exists in the text, otherwise we do a simple regex using '\b' instead.

**Comment by schroedingerscode** [comment]
So I'm sure y'all have put more thought into this than I have, but is just running a `indexOf("\uD83D\uDEA7")` on the input string not a potential solution? `\uD83D\uDEA7` is the Unicode representation for the 🚧 emoji. So basically, if str.indexOf("\uD83D\uDEA7") != -1, the 🚧 emoji is in the string.

**Comment by gr2m** [comment]
We have to check for any emoji as the terms are configurable and people can set it to anything they want

**Comment by schroedingerscode** [comment]
While this approach should work for any single character in UTF-8 (including emojis),  it would get a little squirrelly is if someone were to define a term that included both an emoji and some other chars. 

However, I don't see why this approach won't still work using traditional Perl regex. Just use surrogate pairs (in the case of ES5) or unicode code point escapes (in the case of ES6) in the Regex and you're good to go. I'll work on a PR for this, I actually think it should go pretty quick.

**Comment by gr2m** [comment]
Thanks :)

**Comment by schroedingerscode** [comment]
No problem. I spent a little why digging in to the code and thinking through how I've used this, and I understand the issue now. 

It's not necessarily a word length issue (where regex is treating chars in the astral planes as 2 chars in the BMP), but it's an issue with wanting to enforce word boundaries for terms entirely within the BMP, but not for chars in the astral plan such as emojies. 

Given my assumption above, this begs the question: How do we treat a term which mixes emojies and \w chars? i.e. (🚧Test). Should "Explanation🚧Test" match? My initial impression is that only standalone emojies are special. Everything else should only be tested across word boundaries. If you're good with that @gr2m, I'll jam and update the readme in a non-intrusive way to explain that behavior.

**Comment by schroedingerscode** [comment]
Just about got my PR ready, and I'll leave a note explaining this in the PR, but can you confirm which Node version you're running the deployed app on? 

Having access to ECMAScript 2018 RegExp look behinds makes this feasible, and that feature seems to be supported in Node v8.10.0 and later. It is also supported in >=8.3.0 (from the package.json engines) as long as the --harmony flag is given.

**Comment by gr2m** [comment]
Node 10.15
