### ISSUE TITLE
Checks are occasionally slow

### ISSUE THREAD

**Issue by paulmelnikow** [wip/app#162]
Hi! Thanks so much for your work on this useful tool 😄

Occasionally, a PR will show "Waiting for status to be reported" for a long time. For a while this was pretty common, and then a few months ago it stopped happening.

In the Shields repo we've got WIP configured as a required check, so when this does happen, it can be a problem.

I've got one now that seems stuck 8 minutes later:

<img width="783" alt="screen shot 2018-12-04 at 5 14 08 pm" src="https://user-images.githubusercontent.com/1487036/49476462-0ac5ab00-f7e8-11e8-8682-eff118ba580b.png">

1. Is pushing another commit the best way to kick one of the checks? Is there any way to do it by hitting a URL or through a UI? (Unfortunately, pushing a commit dismisses PR reviews.)
2. Any thoughts on what might be causing this?

**Comment by paulmelnikow** [comment]
It's not just this PR; it's happening on many of our PRs. Maybe something is down.

**Comment by gr2m** [comment]
Hey Paul, sorry for the trouble! Yes there was a spike of errors today, but only 8:15am —  10:15am, then around 12pm Zeit’s now (where WIP is deployed) experienced problems: https://zeit-status.co. It seems to be resolved now. Could you tell me if the problem persists?

WIP usually should create the check within 5s. If it takes longer than sometimes it’s a delay of GitHub’s webhook requests, so it's a good idea to watch their status page, too. I’ll link it all from the README.

WIP itself has no persistence / queue system, so I don’t think it’s WIP’s code that’s causing delay.

And sometimes WIP is hitting rate limits and abuse rate limits, I'm working on that right now

**Comment by jwsloan** [comment]
This has been happening for us as well. Any additional thoughts, @gr2m ?

**Comment by gr2m** [comment]
I started tracking durations of responses to the webhook events sent by GitHub

![image](https://user-images.githubusercontent.com/39992/50016969-90332300-ff7f-11e8-8fa4-c87ba4f18d3e.png)

I think this is somehow related to #151. I know that the GitHub Slack App team saw something similar , too. They use probot as well, I'll ask them if they found out anything new

**Comment by jwsloan** [comment]
This continues to be a problem for us. Any idea what's going on @gr2m?

**Comment by gr2m** [comment]
Right now there is an outage, I’m not sure what’s going on I’m afraid. I’ve contacted @zeit, their status page does not show any problem though: https://zeit-status.co/

I’m currently focussing on upgrading Probot which will have a much better implementation of request throttling and retries, I hope that this will already help.

**Comment by jwsloan** [comment]
Thanks for the quick reply, @gr2m! Any idea of your timeline for the Probot upgrade?

**Comment by gr2m** [comment]
... and we are back! 

> Thanks for the quick reply, @gr2m! Any idea of your timeline for the Probot upgrade?

Soon! Watch this place: https://github.com/probot/probot/pull/774

**Comment by gr2m** [comment]
Things should be much better now. I don’t see any duration spikes any longer, it’s fairly constant at around 1.5s

Please let me know if you still experience delays

**Comment by manasesjesus** [comment]
I modified one line to test this app, made a pull request and it's been more than 13 minutes... still in progress :-/

**Comment by gr2m** [comment]
can you share the URL to the PR in question? I can check the logs.
