### ISSUE TITLE
I can merge pull request even after putting "WIP"

### ISSUE THREAD

**Issue by kawamura-miho** [wip/app#166]
Hello, thanks for developing such a nice app.

I installed wip(free version) to my project's repository, and tested it.
When I created the pull request with "WIP" on title, I just got the message, like "WIP In progress — Title contains WIP", and it seemed "Merge pull request" button is active.

Is there something I have to do other than install the app?

I really appreciate your help.
<img width="817" alt="2019-01-11 9 23 20" src="https://user-images.githubusercontent.com/17842261/51006062-da122780-1584-11e9-8554-2bacb177bce2.png">

**Comment by gr2m** [comment]
You also have to enable branch protection: https://help.github.com/articles/about-protected-branches/

In the "Require status checks to pass before merging" setting, you should see "WIP"

![image](https://user-images.githubusercontent.com/39992/51008520-fcfaf800-1500-11e9-9950-b516131055e7.png)

Does that work for you?

**Comment by kawamura-miho** [comment]
oh, great!! It worked!!!!

Thank you soooo much!!

![Uploading スクリーンショット 2018-08-07 18.55.31.png…]()

**Comment by gr2m** [comment]
You are very welcome :)
