### ISSUE TITLE
Question: How does WIP make sure a pr won't be merged?

### ISSUE THREAD

**Issue by MVrachev** [wip/app#169]
I am wondering how the WIP makes sure that a pull request won't merge into master when there is WIP into the label of a PR?

I was searching into the codebase but I couldn't find it.

**Comment by MVrachev** [comment]
Hi again, I am sorry I didn't explain better what I mean.

I asked you this question because there is a setting in every Github repository to choose which Github apps checks should pass in order the pull request to me merged:
![image](https://user-images.githubusercontent.com/16246778/51128994-e4a51900-1831-11e9-9539-52b9be26d809.png)

Do you somehow enforce this setting upon installation or ? 
How do you achieve that?

**Comment by gr2m** [comment]
Apologies Martin, I missed your last question.

The list of "Status checks found in the last week for this repository" is automatically generated by GitHub. When your app creates a status check or commit status, it will be listed there for a week. There is no dedicated API to have your app listed.

**Comment by MVrachev** [comment]
Thank you for your answer! :))
