### ISSUE TITLE
 WIP Expected — Waiting for status to be reported 

### ISSUE THREAD

**Issue by nicain** [wip/app#174]
PR is stuck (xref https://github.com/wip/app/issues/109, seems like the same issue)

https://github.com/AllenInstitute/visual_behavior_analysis/pull/440

This issue probably deserves a support tag.  Thanks for your help!

**Comment by gr2m** [comment]
There is a new memory leak in the app which causes it to restart every ~7h. In the last minutes before the restart the duration goes up exponentially, but not as bad as it was when #109 was reported.

When you change the title, does that help?

Also it looks like you didn’t update to the new version, you have to accept the new permissions. A prompt should show up at https://github.com/apps/wip/installations/new

**Comment by nicain** [comment]
Bingo!  that worked like a charm! Thanks for your help, and your awesome product.
