### ISSUE TITLE
About the new GitHub Draft Pull Request feature

### ISSUE THREAD

**Issue by brunolemos** [wip/app#177]
So... GitHub just launched a way to create WIP Pull Requests.
https://github.blog/2019-02-14-introducing-draft-pull-requests/

Does this make WIP obsolete?
What are your thoughts about this?
Did they talk to you? Specially because it's something that was on their marketplace.

**Comment by gr2m** [comment]
It’s all good, I’m glad they landed the feature! I know for a fact that this was a highly requested feature long before there even was a Marketplace. This is part of GitHub’s "Paper Cuts" project: https://github.blog/2018-08-28-announcing-paper-cuts/

I’m not yet sure if it will make WIP obsolete or not, the APIs for the new feature are not yet shipped. Maybe there are some use cases not covered by the feature, it’s too early to tell.

Thanks for opening the issue, I’m sure lots of folks are wondering the same thing right now

**Comment by brunolemos** [comment]
> It’s all good, I’m glad they landed the feature!

Ok, good to know!

**Comment by gr2m** [comment]
One thing that the new feature does not support is to flag a pull request as work in progress after the "ready for review" button was pressed

**Comment by arnested** [comment]
Draft Pull Requests API: https://developer.github.com/changes/2019-02-14-draft-pull-requests/

From a quick look it doesn't appear to possible to go back to a draft state after being in "Ready for review".

**Comment by travi** [comment]
theres at least already been [some feedback](https://twitter.com/lukehefson/status/1096102852248903681) around that, but that is the case for the time being

**Comment by zrytos** [comment]
ZaZalew

**Comment by gr2m** [comment]
The Draft feature has been out for a while now and WIP is still going strong :) I think people like the use of it and the configurability. They also like that a pull request can switch back and forth between the WIP status, which the draft PR feature still cannot.

Let me know why you stick with WIP, I want to give it some love and will focus on features that make it worthwhile despite the new draft feature

**Comment by gabel** [comment]
For us are WIP and Draft PR two meanings. 

* We use DNP (do not process) flag to mark PRs in the manner of draft and not ready to get reviewed - they are open for discussion but usually are in a very early stage
* WIP is used in a later state e.g. during code review and test phase and if reviewer has signed of the PR the WIP can be removed as code-reviewer and merger are not the same person by default. 

For us WIP is still relevant, even with draft PRs.

**Comment by gr2m** [comment]
> Does this make WIP obsolete?

After 9 months I can confidently say: no, it doesn't make WIP obsolete. The app usage is consistently growing :)
