### ISSUE TITLE
Configure default locations for "organization"

### ISSUE THREAD

**Issue by rickalm** [wip/app#203]
Ok I did browse the source to see if something like this was tucked away somewhere

Rather than having to configure in each repo a .github/wip.yml to enable checking labels I want to be able to configure that at an organization level. 

Don't know enough about github to know if there is a place the plugin can stash a config, or maybe support a special repo in the org that contains the config file ?

Thanks

**Comment by gr2m** [comment]
Hello @rickalm,

you can create a repository with the name `.github`, then within that repository create the `.github/wip.yml` file. I've documented it here: https://github.com/wip/app#configuration - is it maybe not clear enough?

**Comment by gr2m** [comment]
Here is an example: https://github.com/gr2m/.github/blob/master/.github/wip.yml

**Comment by rickalm** [comment]
Excellent thanks. Yeah docs are not clear enough and I didn't see any comments in the code

On July 31, 2019 6:29:03 PM CDT, Gregor Martynus <notifications@github.com> wrote:
>Hello @rickalm,
>
>you can create a repository with the name `.github`, then within that
>repository create the `.github/wip.yml` file. I've documented it here:
>https://github.com/wip/app#configuration - is it maybe not clear
>enough?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/wip/app/issues/203#issuecomment-517059379

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gr2m** [comment]
The app is using [Probot](https://probot.github.io/), the central configuration is a built-in feature, hence no code comments.

PRs welcome to clarify the documentation. Glad you got it working now :)
