### ISSUE TITLE
look in labels by default for pro accounts

### ISSUE THREAD

**Issue by cyberhck** [wip/app#210]
by default support labels for WIP, if a label clearly says `WIP` or `wip` or `Work In Progress` I think it shouldn't require a presence of wip.yml file, it's kinda tedious to have to do this in each repo, can we add that please?

**Comment by cyberhck** [comment]
or is there a env variable I can set while deploying this app for our internal github? which will check labels even though there's no wip.yml file? I ask this because you had documented somewhere on premarket place it used to do so.

**Comment by gr2m** [comment]
>  it's kinda tedious to have to do this in each repo, can we add that please?

you can create a `.github` repository, and in that repository create the `.github/wip.yml` file, that will apply to the whole owner (your personal account or organization).

Does that work for you?

It's all stated in the README: https://github.com/wip/app#configuration which is linked for the Marketplace page: https://github.com/marketplace/wip/

I don't know how to make that more prominent to make sure it doesn't get missed ...

**Comment by cyberhck** [comment]
Thanks, I missed that,
