### ISSUE TITLE
WIP is being removed from GitHub Marketplace

### ISSUE THREAD

**Issue by rickalm** [wip/app#214]
We were notified that WIP is being dropped from the Marketplace.

Can anyone provide more information @gr2m ??

**Comment by rickalm** [comment]
apparently related to invoiced billing through Github

**Comment by gr2m** [comment]
I heard no such thing, curious! Thanks for letting me know! Can you share the invoice with me? I’ll check in with GitHub

**Comment by gr2m** [comment]
I've contacted GitHub Support for clarification

**Comment by gr2m** [comment]
Hi Rick,

GitHub support got back to me:

> Thanks for reaching out, apologies for the delayed response! I've checked with our engineering team, and they have confirmed that we don't have any plans to pull any apps.
>
> Did this person receive an official notification? If they did, could you please ask them to send it to us so we can take a closer look at what/why it was sent?

Could you please forward the notification you received to support@github.com?

**Comment by rickalm** [comment]
Sorry since I first started this the situation became clearer to me.

We switched from 'credit card' billing to 'invoice' billing. When that happens GitHub stops supporting the ability to sign up for things like WIP though the site and their answer is 'just contact the vendor and make arrangements.

Having poked around the code I know to keep things simple you rely on the GitHub subscription API to know if someone is part of the program and the only way now is

Figure out how to pay
List our org as 'free'

All of which is unreasonable burden vs them having a plan

On December 3, 2019 1:40:10 PM CST, Gregor Martynus <notifications@github.com> wrote:
>Hi Rick,
>
>GitHub support got back to me:
>
>> Thanks for reaching out, apologies for the delayed response! I've
>checked with our engineering team, and they have confirmed that we
>don't have any plans to pull any apps.
>>
>> Did this person receive an official notification? If they did, could
>you please ask them to send it to us so we can take a closer look at
>what/why it was sent?
>
>Could you please forward the notification you received to
>support@github.com?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/wip/app/issues/214#issuecomment-561324446

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
