### ISSUE TITLE
WIP frozen

### ISSUE THREAD

**Issue by pniedzwiedzinski** [wip/app#216]
It looks like the WIP app died 😭 
https://github.com/zsk-poznan/zastepstwa-gui/pull/13/checks?check_run_id=349393336
It runs for over 15 minutes now.

**Comment by pniedzwiedzinski** [comment]
Also, as I'm writing I want to tell that I love this plugin. I use it a lot and it makes my life easier. I'm very grateful to you for making it.

**Comment by gr2m** [comment]
Hey could you try to edit the title and see if that resolves the pending status? I’ll check the logs if I can find a problem tomorrow

**Comment by pniedzwiedzinski** [comment]
I changed it and it’s still frozen. But new commits pass. So it works now but the old one is still frozen.

**Comment by gr2m** [comment]
okay thanks, glad that it worked now. I'll see if I can find out something about the frozen state

**Comment by gr2m** [comment]
Is this still a problem?

**Comment by pniedzwiedzinski** [comment]
It still freezes from time to time, but as it is 'working' it blocks PR from being merged so it's okay. Although sounds invalid

**Comment by gr2m** [comment]
I'm working on making the app more resilient. It's going to take a bit more time, but I'll get back to you once it's out

**Comment by chdsbd** [comment]
I've been experiencing reliability issues recently where WIP isn't setting a status check.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/1929960/89798610-60447600-dafa-11ea-8c6e-19e5d8a8c506.png">

**Comment by gr2m** [comment]
You are using the beta version? Can you uninstall it https://github.com/apps/wip-beta and install the WIP app instead? https://github.com/apps/wip

**Comment by chdsbd** [comment]
Thanks for the quick response.

I'll try that new app.

Out of curiosity, why might the new one be more reliable than the other?

**Comment by gr2m** [comment]
https://github.com/apps/wip-beta  is just for testing, I do not monitor it

**Comment by AraHaan** [comment]
Question, is it possible to be able to tell the WIP bot that when it finds anything to make it see that it is a ``WIP`` that I can tell the bot to report a check failure status?

This is because I am migrating to the mergify system for my open source project and I do not know if there is a way to do an ``check-pending=WIP`` condition where it will send a message saying ``This PR is WIP, when you complete the work remember to unset the WIP state in the title of this PR.``

**Comment by gr2m** [comment]
Sorry I think what you are asking for is out of scope for WIP, but I don't 100% get it, can you create a separate issue? Also read the README, all of it ;)

**Comment by Nikoloutsos** [comment]
Another incident happened for me today. The wip was frozen to pending. While other PR's pass

**Comment by gr2m** [comment]
Can you share the pull request URL? If the repository is private, at least the repository login and pull request number?

The logs look good to me, so it was either a temporary hiccup with WIP, or a problem with your installation

**Comment by Nikoloutsos** [comment]
@gr2m Glad to share with your but it's on Github Enterprise.
Here is the problem I found:

After installing the wip in our **private repo** it would not work correctly for older PRs. New  PRs were working good.
After some debugging we found that the wip gets 403 http status when changing the older PRs.

Have you seen this again? It may be a bug of wip

**Comment by AraHaan** [comment]
I do not think it is a bug, try to see if you can push a fake update to those old PR's and see if they will work after that:

You could try something like so:

``git rebase -i HEAD~1``
change ``pick`` to ``edit``.
Save without changes so it gets a new commit hash
force push.

And then check if WIP is updated for those PR's.
