### ISSUE TITLE
WIP status check not appearing in the returned statuses for a reference

### ISSUE THREAD

**Issue by nazrhom** [wip/app#217]
I noticed something odd, when trying to fetch the list of status checks associated with a specific reference (e.g. via `octokit.listStatusesForRef`). The `WIP` status check is missing, I tried fetching the using the head SHA as a reference (which matches what I see in https://github.com/wip/app/blob/master/lib/free/set-status.js#L12) and also using the branch... but both give the same results.
Is this expected? Ill try to setup a minimal test case to reproduce this

**Comment by nazrhom** [comment]
Turns out these do not appear in the status API, but actually as [checks](https://developer.github.com/v3/checks/). Sorry for the noise :)

**Comment by gr2m** [comment]
The statuses can be set by both, commit statuses and check runs. It's all a bit confusing :/ but if you ever need to get the list of all status for a commit then you need to load both.
