### ISSUE TITLE
WIP sending lots of very old “WIP checks stale” notifications 

### ISSUE THREAD

**Issue by Perksey** [wip/app#228]
These notifications are being sent to a webhook connected to a discord channel. They’re all stale notifications, and they’re all very old (some on deleted branches). If any of the WIP team have discord, see dev-feed in this channel: https://discord.gg/DTHHXRt

**Comment by gr2m** [comment]
Looks like a duplicate to https://github.com/wip/app/issues/227. But you answered my question from https://github.com/wip/app/issues/227#issuecomment-592027005 and confirmed my suspicion: WIP is _not_ sending these events. The `stale` action is special, github itself sets check runs that have been set to "pending" for 14 days to stale. You can ignore them

You can learn more about these events at https://developer.github.com/changes/2020-02-03-stale-conclusion/

**Comment by Perksey** [comment]
Ah this must be a relatively new change and I was unaware of this, thanks for letting me know! I will remove `stale` checks from my webhook :)
