### ISSUE TITLE
How to address the issue of your GitHub App being down(just in case)

### ISSUE THREAD

**Issue by akmalick** [wip/app#234]
@gr2m  Just wanted to know how do you deal with the downtime. You have your WIP app hosted somewhere. What if the app is down or somehow not reachable. How is this scenario handled? If I develop an app that in future could possibly be used by thousands of people, then what do I need to address that?

I had posted the question at StackOverflow too : 

https://stackoverflow.com/questions/61789327/how-to-address-the-issue-of-a-particular-github-integration-being-not-reachable

Is it OK(ethically/as per guidelines) to post question on stackoverflow and then link it here, or do I need to provide the complete question here.

**Comment by gr2m** [comment]
> Is it OK(ethically/as per guidelines) to post question on stackoverflow and then link it here, or do I need to provide the complete question here.

Totally fine 👍 But I'll close the issue here and respond on StackOverflow if you don't mind :)

**Comment by akmalick** [comment]
> > Is it OK(ethically/as per guidelines) to post question on stackoverflow and then link it here, or do I need to provide the complete question here.
> 
> Totally fine 👍 But I'll close the issue here and respond on StackOverflow if you don't mind :)

I'm fine with that :)
