### ISSUE TITLE
WIP blocks merging if commit message contains "wip"

### ISSUE THREAD

**Issue by FelixReuthlingerBMW** [wip/app#240]
I found it a bit hindering that the WIP bot was blocking to merge a PR if there is a commit that contains one of the marking flags that the bot is looking for. Commit messages should not be blocking the PR, since those should show a history and not be marking the PR forever.

**Comment by gr2m** [comment]
Hi Felix, is that on your personal account or an organization? By default, WIP does not consider commit messages at all. But it is configurable if you subscribed to pro or enterprise plans: https://github.com/marketplace/wip/

**Comment by FelixReuthlingerBMW** [comment]
I had this problem inside our Github organisation that contains multiple projects, if that is what you referring to. I am not sure if we are using pro or enterprise, how can I find out? I am not admin there, so, cannot see all configurations probably.
I will ask some of our admins about that, but thanks for clarification on this :)

**Comment by gr2m** [comment]
I can find out if you like, I just need to know the name of the GitHub Organisation

**Comment by FelixReuthlingerBMW** [comment]
We are running our corporate private Github organisation inside our network, doesn't have public access.

**Comment by gr2m** [comment]
Got it. In that case, the pro features should be enabled automatically. Look for a `.github/wip.yml` file in the repository in question, or in a `.github` repository in the same organization. See https://github.com/wip/app#configuration

**Comment by FelixReuthlingerBMW** [comment]
Thanks for the hint ;)
