### ISSUE TITLE
WIP Server seems to be hanging

### ISSUE THREAD

**Issue by JoshuaSBrown** [wip/app#324]
I could be wrong but it looks like the WIP server is hanging. This morning removing WIP from the title of a pr does not appear to be working. It just hangs with:

WIP Expected — Waiting for status to be reported 

https://github.com/lanl/parthenon/pull/479

Removing and adding WIP to the title does not appear to change anything.

**Comment by gr2m** [comment]
can you please double check with the wip app is installed on on the repository?

**Comment by JoshuaSBrown** [comment]
Ok that was the problem, sorry for wasting your time. Thanks.
