### ISSUE TITLE
The user data can't be public

### ISSUE THREAD

**Issue by Chizkiyahu** [wip/app#565]
The list of users and the numbers of PR per user can't be public

https://github.com/wip/app/blob/097f668c93b03fdad485fcc8d6b5953a600bca28/public/stats/index.html#L21

**Comment by gr2m** [comment]
it's already publicly visible when WIP is installed. Why do you think I can't display this information?

**Comment by Chizkiyahu** [comment]
Users using this on their private repo 
and they on the list 
Even the number one on the list ( at the time that I check ) don’t have public repo at all

**Comment by gr2m** [comment]
Okay I still don't understand how this is a problem. If I missed some of GitHub's user privacy requirements then please let me know, I'll definitely address it. But if this is your opinion then I'm sorry, I'm not going to address it.
