### ISSUE TITLE
Changing Title after Build kicks off makes WIP stuck

### ISSUE THREAD

**Issue by michael-hawker** [wip/app#595]
Related to #58

![image](https://github.com/wip/app/assets/24302614/7f899560-3969-493f-adee-0cb06914dcd5)

PR: https://github.com/CommunityToolkit/Windows/pull/204/checks?check_run_id=16357745427

But the title no longer contains the character.

How can I dismiss or get WIP to recheck this? I tried adding a comment per the readme, but nothing happened.

**Comment by gr2m** [comment]
Hmmm it should create a new check run and as it's the same name it should override the old one. 

The reason this didn't work this time was most likely due to today's incident with webhooks:
https://www.githubstatus.com/incidents/f7lz4nc72bvp

Can you try to reproduce the problem now?

**Comment by michael-hawker** [comment]
Ah, thanks for the response @gr2m, I already merged our PR as we're trying to ship, so I had just turned off the mandatory check for WIP and then turned it back on after... 😋

Will let you know if we see it again.
