### ISSUE TITLE
New to GitHub App

### ISSUE THREAD

**Issue by meetDeveloper** [wip/app#621]
Hey,

I was learning how to develop GitHub App and wanted to see open source code of GitHub Apps, and I found out about your app through that.

I had a query, I installed your app, but I am not sure how is it working, as far as I understand, after installation, you must have received a access token valid on my GitHub account but where did you stored that access token, as I never created account on WIP app website. 

How and when is WIP app using the access token which it receives when I installed on my account.

I think I am not getting something.

Thanks, I know this is not traditional issue. I did not knew any other way to ask this. :(

**Comment by gr2m** [comment]
> I had a query, I installed your app, but I am not sure how is it working, as far as I understand, after installation, you must have received a access token valid on my GitHub account but where did you stored that access token, as I never created account on WIP app website.

The act of installing an app grants the app access to all repositories that you added to that installation. With the credentials of the WIP app (ID and private key) and the ID of your installation, I can now create an installation access token. Using that token, I can now interact with resources in the repositories you granted the app access to, limited by the requested permission of the app.

The way the WIP works, and most GitHub Apps for that matter, is this

1. GitHub sends a webhook request for a pull request to the configured URL of the WIP app. For example, the `pull_request` events are handled here: https://github.com/wip/app/blob/5476d4a5184d56bbed7edf8872e9952491feb4fe/index.js#L12-L21
2. The payload includes the installation ID. The app is using that installation ID to create an access token. This is all taken care of by Octokit, GitHub's Official SDK. The webhook handler callback receives an object with an `.octokit` property, which is the octokit instance that is pre-authenticated using the installation access token. See this documentation for more information: https://github.com/octokit/octokit.js#webhooks

Hope that helps! I'll close this issue as there is nothing actionable for me, but feel free to ask follow up questions.
