### ISSUE TITLE
WIP Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by alexdeng-mp** [wip/app#660]
Hi,

We've started having `WIP Expected — Waiting for status to be reported` reported on all of our PRs starting today.
Seems to be the same as https://github.com/wip/app/issues/174.
Please let me know if theres any extra debugging information I can pass on.

**Comment by jonghyun-kim** [comment]
Same here - `WIP Expected — Waiting for status to be reported`

**Comment by PaulvanMotman** [comment]
Same here

**Comment by Borda** [comment]
we have the same problem, see for example: https://github.com/Lightning-AI/pytorch-lightning/pull/19442

**Comment by andrew-garland** [comment]
First noticed this yesterday 4pm eastern

**Comment by singhsBSRS** [comment]
Same here. We have disabled this plugin for the time being

**Comment by jmeattle** [comment]
cc @gr2m

**Comment by SlevinWasAlreadyTaken** [comment]
Same here :)

**Comment by gr2m** [comment]
Sorry folks, there was a problem yesterday for a short time, I thought I resolved it. Looking into it now

**Comment by gr2m** [comment]
I was able to reproduce the problem here: https://github.com/wip/app/pull/661 - sorry for the inconvenience. I'll revert recent changes for now and will be more careful in future.

**Comment by gr2m** [comment]
🤦 I had the webhook URL still pointing to a preview deployment. Should all be working again. I'm very sorry for all that, I'll think about putting in a CD check to verify a new deployment to production is working as expected.

**Comment by jmeattle** [comment]
Thank you @gr2m !

**Comment by ttpaparouni** [comment]
I have pushed a new commit but the "WIP Expected — Waiting for status to be reported" message remains unchanged.

**Comment by gr2m** [comment]
Can you share the URL of the pull request, even if the repository is private? I can look into it. Can you please file a separate issue as a lot of people are subscribed to this one? Thank you!

**Comment by alexdeng-mp** [comment]
@gr2m we're seeing this issue again. Server issues?

**Comment by gr2m** [comment]
Sorry for that, indeed. I accidentally updated to the latest @probot version in #773, I'm surprised that tests passed. I already reverted it via f5a1fcc, it should be resolved momentarily. Sorry for that
