### ISSUE TITLE
T-Shirts and Stickers... 👕✨

### ISSUE THREAD

**Issue by jbialy** [wip/app#72]
In light of the new logo, I propose a `wip` t-shirts and stickers 😸 from redbubble.com 😝

**Comment by micahilbery** [comment]
No objections from me :smile: As far I'm concerned the logo fully belongs to the project now. Like a child that grew up and moved out and I get to watch it grow & change with the project and be proud of it lol. So absolutely feel free to make it into sticker, t-shirts, pins, swag, merch, ect.

**Comment by gr2m** [comment]
They grow up so fast 🤣

**Comment by gr2m** [comment]
I’m gonna close it for now but I’ll get back to it :)

**Comment by jbialy** [comment]
Sounds good!
