### ISSUE TITLE
does not support "[WIP]"? (update: it of course does!)

### ISSUE THREAD

**Issue by myakura** [wip/app#97]
I see a lot of issues using wip keywords wrapped in brackets (e.g ["[WIP]"](https://github.com/search?q=wip&type=Issues)). However, the current code to check whether the issue is a work in progress it does not support that pattern.

https://github.com/wip/app/blob/88f6c675f10baabc40b62b77ff7e7fcce92492f8/lib/handle-pull-request-change.js#L47-L49

Notice the leading `\b`. It doesn't treat brackets as word boundaries so it fails to catch issues titled "[WIP] blah".

**Comment by gr2m** [comment]
Hi @myakura, I’m pretty sure that it will it supports having `"[WIP]"` in the title. You can run this code in your browser console to check:

```js
/\b(wip|do not merge|work in progress)\b/i.test('[WIP]') // returns true
```

I also tested it here and it works as expected: https://github.com/gr2m/sandbox/pull/41

**Comment by gr2m** [comment]
Do you have a pull request in a public repository where it does not work? Can you give me a link to it?

**Comment by myakura** [comment]
Okay, it looks like the bot doesn't work on PRs that already have the keywords before installing the app. Is that an intended behavior?

**Comment by gr2m** [comment]
The app only sets the status when a PR gets changed. It doesn’t check existinf PRs. But that might be a good idea :)

**Comment by myakura** [comment]
@gr2m thanks!

**Comment by gr2m** [comment]
closing in favor of https://github.com/wip/app/issues/98
